services:

  mysql-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    image: springboot-app
    depends_on:
      - mysql-db
    ports:
      - "8090:8090"

volumes:
  mysql-data: