spring.application.name=SecurityImpl
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3307/security1
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.type.descriptor.sql=TRACE

# Optional but recommended (Docker timing issue fix)
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.connection-timeout=60000